// Synonym groups: each line is a set of interchangeable terms (lower case). Like ABBR in match.js,
// they are only tried when a typed answer matches no tile, so a tile keyed on one term still
// accepts the others. Keep terms specific; avoid words that mean different things in other contexts.
export const SYNONYMS = [
  // signs and symptoms
  ["erythema", "redness"],
  ["fever", "pyrexia", "febrile"],
  ["oedema", "swelling"],
  ["dyspnoea", "breathlessness", "shortness of breath"],
  ["haematuria", "blood in urine"],
  ["haemoptysis", "coughing blood", "coughing up blood"],
  ["haematemesis", "vomiting blood"],
  ["melaena", "black stool", "black stools"],
  ["pruritus", "itch", "itching"],
  ["jaundice", "icterus", "yellow skin"],
  ["pallor", "pale"],
  ["tachycardia", "fast heart rate", "rapid pulse"],
  ["bradycardia", "slow heart rate", "slow pulse"],
  ["hypertension", "high blood pressure"],
  ["hypotension", "low blood pressure"],
  ["syncope", "fainting", "blackout", "collapse"],
  ["vertigo", "room spinning", "spinning"],
  ["dizziness", "lightheaded", "light headed"],
  ["palpitations", "racing heart"],
  ["dysuria", "painful urination", "burning urination"],
  ["polyuria", "frequent urination", "passing a lot of urine"],
  ["dysphagia", "difficulty swallowing", "trouble swallowing"],
  ["odynophagia", "painful swallowing"],
  ["anorexia", "loss of appetite", "poor appetite", "reduced appetite"],
  ["weight loss", "losing weight"],
  ["weight gain", "gaining weight"],
  ["cachexia", "wasting"],
  ["alopecia", "hair loss"],
  ["diarrhoea", "loose stools", "loose stool"],
  ["fatigue", "tiredness", "lethargy"],
  ["myalgia", "muscle pain", "muscle aches"],
  ["arthralgia", "joint pain", "joint aches"],
  ["tremor", "shaking"],
  ["seizure", "fit", "convulsion"],
  ["paraesthesia", "pins and needles", "tingling"],
  ["nausea", "feeling sick"],
  ["epistaxis", "nosebleed", "nose bleed"],
  ["otalgia", "ear pain"],
  ["rhinorrhoea", "runny nose"],
  ["dyspepsia", "indigestion"],
  ["rigors", "shivering", "chills"],
  ["photophobia", "light sensitivity", "sensitivity to light"],
  ["diplopia", "double vision"],
  ["tinnitus", "ringing in ears", "ringing in the ears"],
  ["hirsutism", "excess hair", "excessive hair"],
  ["amenorrhoea", "absent periods", "missed periods"],
  ["menorrhagia", "heavy periods"],
  ["hepatomegaly", "enlarged liver"],
  ["splenomegaly", "enlarged spleen"],
  ["lymphadenopathy", "enlarged lymph nodes", "swollen glands"],
  ["cyanosis", "blue lips"],
  ["wheeze", "wheezing"],
  ["haemorrhage", "bleeding"],
  ["anaemia", "low haemoglobin"],
  ["hyperglycaemia", "high blood sugar"],
  ["hypoglycaemia", "low blood sugar"],
  ["hypoxia", "low oxygen"],
  ["incontinence", "leaking urine"],
  // diagnoses
  ["myocardial infarction", "heart attack"],
  ["stroke", "cerebrovascular accident"],
  ["heart failure", "cardiac failure"],
  // organ adjectives
  ["kidney", "renal"],
  ["liver", "hepatic"],
  ["lung", "pulmonary"],
  ["heart", "cardiac"],
  ["brain", "cerebral"],
  ["stomach", "gastric"],
  ["skin", "cutaneous"],
  // investigations and misc
  ["x-ray", "xray", "radiograph"],
  ["stool", "faeces", "faecal"],
  ["blood sugar", "glucose"],
  ["diabetes", "bsl", "bgl", "sugar", "sugars"],
  ["smoking", "tobacco", "cigarettes"],
  ["operation", "surgery"],
];
